name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: transferwise/actions-bootstrap-node@v1
        with:
          package-manager: pnpm
          npm-token: ${{ secrets.NPM_TOKEN_READONLY }}
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run --if-present test

  release-latest:
    name: Release latest version
    needs: [build-lint-test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: transferwise/actions-bootstrap-node@v1
        with:
          package-manager: pnpm
          npm-token: ${{ secrets.NPM_TOKEN_AUTOMATION }}
      - run: pnpm run build
      - name: Set up commit signing
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGN_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Create release PR or publish on npm
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
          commit: "chore: release"
          title: "chore: release new version and update changelog"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
